# Generated by Django 3.2.4 on 2021-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Notes',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
