# Generated by Django 3.2.4 on 2021-07-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_task_user'),
    ]

    operations = [
    ]
