# Generated by Django 3.2.4 on 2021-07-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20210718_1233'),
    ]

    operations = [
    ]
