# Generated by Django 3.2.4 on 2021-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
